In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.2.6


In [4]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [5]:
my_list = my_list *2
my_list

[1, 2, 3, 4, 1, 2, 3, 4]

In [6]:
array = np.array([1,2,3,4])
print(type(array))

<class 'numpy.ndarray'>


In [7]:
array = array *2
array

array([2, 4, 6, 8])

In [ ]:
array = np.array('a')
print(array.ndim)

0


In [ ]:
array = np.array(['a','b','c'])
print(array.ndim)

1


In [3]:
array = np.array([['a','b','c'],['e','f','g'],['h','i','j']])
print(array.ndim)

2


In [4]:
array = np.array([[['a','b','c'],['d','e','f'],['g','h','i']],
                  [['j','k','l'],['m','n','o'],['p','q','r']],
                  [['s','t','u'],['v','w','x'],['y','z','?']]])
print(array.ndim)


3


In [ ]:
print(array.shape)

(3, 3, 3)


In [ ]:
print(array[0][0][0])
print(array[0,0,1])

a
b


In [5]:
word = array[0,0,0] + array[0,0,0] + array[2,0,0]
word

'aas'

In [ ]:
a1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# slicing  array[start:end:step]

print(a1[1:4])


[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print(a1[0:4:3])

[[ 1  2  3  4]
 [13 14 15 16]]


In [ ]:
print(a1[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
print(a1[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


In [ ]:
print(a1[:,1])

[ 2  6 10 14]


In [ ]:
print(a1[:,1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [ ]:
print(a1[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [ ]:
a1[0:2,2:4]
a1[2:,0:2]

array([[ 9, 10],
       [13, 14]])

In [ ]:
# Scalar airthemetic

a2 = np.array([1,2,3])
print(a2+1)
print(a2-2)
print(a2*3)
print(a2/4)
print(a2 **5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [ ]:
# vectorized math function
a3 = np.array([1.01,2.5,3.99])

print(np.sqrt(a3))
print(np.round(a3))
print(np.floor(a3))
print(np.ceil(a3))
print(np.pi)

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793


In [ ]:
radii = np.array([1,2,3])

print(np.pi * radii **2)

[ 3.14159265 12.56637061 28.27433388]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
# comparisions operator
scores = np.array([91,55,100,73,82,64])
print(scores ==  100)
print(scores >=  60)
print(scores >  100)

[False False  True False False False]
[ True False  True  True  True  True]
[False False False False False False]


In [ ]:
scores[scores<60]=0
print(scores)

[ 91   0 100  73  82  64]


In [ ]:
# broad casting

In [ ]:
arr1 = np.array([[1,2,3,4]])
arr2 = np.array([[1],[2],[3],[4]])
print(arr1.shape)
print(arr2.shape)

(1, 4)
(4, 1)


In [ ]:
print(arr1 * arr2)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr2 = np.array([[1],[2],[3],[4]])
print(arr1.shape)
print(arr2.shape)

(4, 4)
(4, 1)


In [ ]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(array1 * array2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [ ]:
# aggregarte functions

array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print(np.sum(array))
print(np.mean(array))
print(np.median(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))
print(np.sum(array, axis=1))

55
5.5
5.5
2.8722813232690143
8.25
1
10
0
9
[15 40]


In [ ]:
# filtering
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])
teenagers = ages[ages <18]
adults = ages[(ages>=18) & (ages <65)]
seniors = ages[ages>=65]
evens = ages[ages % 2 ==0]
odds = ages[ages % 2 !=0]
print(teenagers)
print(adults)
print(seniors)
print(evens)
print(odds)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]


In [ ]:
adults = np.where(ages>=18, ages, 0)
adults

array([[21,  0, 19, 20,  0, 30, 18, 65],
       [39, 22,  0, 99, 18, 19, 20, 21]])

In [ ]:
# random numbers

In [ ]:
rng = np.random.default_rng(seed=1)
print(rng.integers(1, 1001,(10,10)))

[[474 512 756 951  35 145 823 949 250 312]
 [870 424 274 828 257 410 644 550  86  28]
 [866 754 838 539 818 330 453 789 124 304]
 [125 454 977 135 384 404 904 204 503 263]
 [ 20 751  63 281 499 486 117 981 750 962]
 [ 93 725 294 542 925 277 726 161 323 970]
 [422 517 293 116 425 624 456 777 363 614]
 [773 918 428  40 719 529 873 460 369  63]
 [458 642 771 853 215 593 805 261 345 840]
 [582 510 674 511 981 754  55 148 546 820]]


In [ ]:
np.random.seed(seed=1)
print(np.random.uniform(low=-1,high=1, size=(5,5)))

[[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822]
 [-0.81532281 -0.62747958 -0.30887855 -0.20646505  0.07763347]
 [-0.16161097  0.370439   -0.5910955   0.75623487 -0.94522481]
 [ 0.34093502 -0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523  0.7527783 ]]


In [ ]:
rng = np.random.default_rng()
array = np.array([1,2,3,4,5])
rng.shuffle(array)
array

array([3, 2, 4, 1, 5])

In [ ]:
rng = np.random.default_rng()
fruits = np.array(["apple","orange","banana","coconut","pineapple"])
fruits = rng.choice(fruits, size=(3,3))
print(fruits)

[['apple' 'coconut' 'banana']
 ['apple' 'apple' 'apple']
 ['coconut' 'banana' 'orange']]
