In [1]:
import numpy as np

In [2]:
prices = np.array([1200, 850,400, 3500])

In [5]:
my_marks = np.array([40,55,70,90])
my_marks += 5
my_marks

array([45, 60, 75, 95])

In [6]:
print(my_marks.ndim)

1


In [8]:
list1 = [1,2,3,4,5,6,7,8,9,10]
array1 = np.array(list1)

In [9]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
print(np.zeros(4))
print(np.ones(10))
print(np.arange(0,10,2))
print(np.linspace(0,.5,100))


[0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 2 4 6 8]
[0.         0.00505051 0.01010101 0.01515152 0.02020202 0.02525253
 0.03030303 0.03535354 0.04040404 0.04545455 0.05050505 0.05555556
 0.06060606 0.06565657 0.07070707 0.07575758 0.08080808 0.08585859
 0.09090909 0.0959596  0.1010101  0.10606061 0.11111111 0.11616162
 0.12121212 0.12626263 0.13131313 0.13636364 0.14141414 0.14646465
 0.15151515 0.15656566 0.16161616 0.16666667 0.17171717 0.17676768
 0.18181818 0.18686869 0.19191919 0.1969697  0.2020202  0.20707071
 0.21212121 0.21717172 0.22222222 0.22727273 0.23232323 0.23737374
 0.24242424 0.24747475 0.25252525 0.25757576 0.26262626 0.26767677
 0.27272727 0.27777778 0.28282828 0.28787879 0.29292929 0.2979798
 0.3030303  0.30808081 0.31313131 0.31818182 0.32323232 0.32828283
 0.33333333 0.33838384 0.34343434 0.34848485 0.35353535 0.35858586
 0.36363636 0.36868687 0.37373737 0.37878788 0.38383838 0.38888889
 0.39393939 0.3989899  0.4040404  0.40909091 0.41414141 0.41919192
 0.42

In [23]:
print(np.random.randint(0,10, size=(10,10)))

[[6 4 6 6 8 2 0 3 8 0]
 [0 9 9 6 2 1 4 1 3 5]
 [8 2 3 7 5 9 3 3 0 4]
 [5 7 6 4 3 2 4 7 1 4]
 [2 1 0 7 1 9 5 3 9 2]
 [7 7 6 0 9 0 1 5 0 7]
 [5 2 7 1 4 0 0 5 4 1]
 [7 8 7 6 1 8 9 4 5 2]
 [3 9 8 3 2 1 5 9 9 0]
 [9 1 5 5 1 1 5 3 5 3]]


In [25]:
array = np.array([255,480,120,990])
array

array([255, 480, 120, 990])

In [26]:
zero_5 = np.zeros(5)
zero_5

array([0., 0., 0., 0., 0.])

1-D , 2-D, multiple dimensions array 
.ndim is find out how many dimensions
.shape size of each direction like 2-d rows and columns
.dtype return the type of array like int64

In [2]:
grid = np.array([[1,2,3],
                [4,5,6]])


In [3]:
print(grid)

[[1 2 3]
 [4 5 6]]


In [4]:
print(grid.ndim)
print(grid.shape)
print(grid.size)

2
(2, 3)
6


In [5]:
board = np.array([[1,0,1],[0,1,0]])

print(board.ndim)
print(board.shape)
print(board.size)

2
(2, 3)
6


In [11]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
print(a)
print(a.reshape(3,4))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
print(a.reshape(6,2))
print(a.reshape(3,4))
print(a.reshape(12,1))
print(a.reshape(2,6))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [29]:
array = np.arange(1,7)
array

array([1, 2, 3, 4, 5, 6])

In [30]:
array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

Data Types 

In [32]:
marks = np.array(['80',72,91])
print(marks.dtype)

<U21


In [44]:
a = np.array([10,20,30], dtype = float)
a[0] = 15.5
print(a.dtype)
a


float64


array([15.5, 20. , 30. ])

In [81]:
array = np.array([[['a','b','c'],['d','e','f'],['g','h','i']],
                  [['j','k','l'],['m','n','o'],['p','q','r']],
                  [['s','t','u'],['v','w','x'],['y','z','_']]])

print(array[1,1,0],array[2,2,2],array[1,1,0],array[2][0][2],array[2][2][1],array[0][0][0],array[1][1][0],array[1][1][0],array[0][2][2],array[1][0][2],array[2][2][2],array[0][0][0],array[1][1][1],array[2][0][0],array[0][0][0],array[1][2][2],array[0][2][2])

m _ m u z a m m i l _ a n s a r i


In [91]:
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                  [[10,11,12],[13,14,15],[16,17,18]],
                  [[19,20,21],[22,23,24],[25,26,27]]])
for i in range(0,3):
    for j in range(0,3):
        for k in range(0,3):
            print(array[i][j][k] , end=" ")


1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 

In [98]:
# for i,j,k in array:
#     print(array[i][j][k])
print(array[0][0][0])

1


In [82]:
marks = np.array([[80, 72, 91],     # Ali
                  [65, 88, 70],     # Sara
                  [95, 60, 84]])    # Hassan
#                  Eng Maths Sci

print(marks[0])          # row 0 - all of Ali's marks
print(marks[1, 2])       # Sara's Science
print(marks[-1, 0])      # last student, first subject

[80 72 91]
70
95


In [51]:
temps = np.array([[30,32,31],   #karachi
                  [28,29,27]])  #lahore

print(temps[0,1])
print(temps[1,2])

32
27


In [92]:
a = np.array([1,2,3])
b = a.copy()
b[0]= 99

In [95]:
print(a,b)

[1 2 3] [99  2  3]
